# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_id=bnb_core
mod_name=BnB Core
mod_license=MIT
mod_version=1.14-dev
mod_group_id=net.dusty_dusty
mod_authors=Dusty_Dusty
mod_description=Core mod for the Blood and Beauty Modpack

# Dependencies
accessories_version=1.0.0-beta.47+1.20.1
cloth_config_version=11.0.99
curios_version=5.14.1+1.20.1
